import type { Task } from "@/lib/types"

/**
 * Mock tasks for development and testing
 */
export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Design new landing page",
    description: "Create wireframes and mockups for the new product landing page",
    status: "in-progress",
    priority: "high",
    assignee: "Sarah Chen",
    dueDate: "2025-02-15",
    tags: ["design", "frontend"],
    createdAt: "2025-02-01",
  },
  {
    id: "2",
    title: "Implement user authentication",
    description: "Set up OAuth and JWT-based authentication system",
    status: "todo",
    priority: "urgent",
    assignee: "Mike Johnson",
    dueDate: "2025-02-10",
    tags: ["backend", "security"],
    createdAt: "2025-02-02",
  },
  {
    id: "3",
    title: "Write API documentation",
    description: "Document all REST API endpoints with examples",
    status: "completed",
    priority: "medium",
    assignee: "Alex Kim",
    dueDate: "2025-02-05",
    tags: ["documentation"],
    createdAt: "2025-01-28",
  },
  {
    id: "4",
    title: "Fix mobile responsive issues",
    description: "Address layout problems on mobile devices",
    status: "blocked",
    priority: "high",
    assignee: "Sarah Chen",
    tags: ["frontend", "bug"],
    createdAt: "2025-02-03",
  },
  {
    id: "5",
    title: 'Prüfe Statikgutachten „Bürogebäude Ost"',
    description:
      "Überprüfe eingereichte Statikberechnungen und Tragwerksplanung auf Vollständigkeit und Plausibilität gemäß DIN 1055.",
    status: "todo",
    priority: "high",
    assignee: "Clara Hoffmann",
    dueDate: "2025-11-12",
    tags: ["structural", "review", "compliance"],
    createdAt: "2025-11-04",
  },
  {
    id: "6",
    title: 'Koordiniere Baustellenbesichtigung „Wohnanlage Nord"',
    description:
      "Termine mit Bauherr, Architekt und Brandschutzbeauftragtem für Vor-Ort-Termin abstimmen und Protokoll vorbereiten.",
    status: "in-progress",
    priority: "medium",
    assignee: "Thomas Becker",
    dueDate: "2025-11-08",
    tags: ["inspection", "coordination", "meeting"],
    createdAt: "2025-11-03",
  },
  {
    id: "7",
    title: "Aktualisiere Denkmalschutzauflagen Projekt #2025-125",
    description:
      "Neue Auflagen vom Denkmalschutzamt in Genehmigungsunterlagen einarbeiten und an Antragsteller kommunizieren.",
    status: "todo",
    priority: "medium",
    assignee: "Clara Hoffmann",
    dueDate: "2025-11-10",
    tags: ["monument-protection", "documentation", "communication"],
    createdAt: "2025-11-04",
  },
  {
    id: "8",
    title: 'Erstelle Lärmschutzgutachten „Industriepark Süd"',
    description:
      "Automatische Lärmschutzanalyse über EnviroCheck durchführen, Grenzwerte prüfen und Gutachten erstellen.",
    status: "in-progress",
    priority: "high",
    assignee: "EnviroCheck",
    dueDate: "2025-11-11",
    tags: ["environment", "noise", "ai", "report"],
    createdAt: "2025-11-02",
  },
  {
    id: "9",
    title: "Überprüfe Abstandsflächenberechnung Antrag #2025-130",
    description:
      "Prüfe eingereichte Abstandsflächenberechnung auf Einhaltung der Landesbauordnung §6 und markiere Abweichungen.",
    status: "todo",
    priority: "high",
    assignee: "Thomas Becker",
    dueDate: "2025-11-09",
    tags: ["calculation", "compliance", "review"],
    createdAt: "2025-11-04",
  },
  {
    id: "10",
    title: 'Genehmige Nutzungsänderung „Lagerhaus Mitte"',
    description: "Finale Prüfung aller Unterlagen für Nutzungsänderung von Lager zu Bürofläche, Genehmigung erteilen.",
    status: "completed",
    priority: "medium",
    assignee: "BauFlowAI",
    dueDate: "2025-11-05",
    tags: ["approval", "change-of-use", "automation"],
    createdAt: "2025-10-28",
  },
  {
    id: "11",
    title: 'Prüfe Stellplatznachweis „Einkaufszentrum West"',
    description:
      "Überprüfe Stellplatzberechnung gemäß Stellplatzsatzung, prüfe Anzahl und Dimensionierung der Parkplätze.",
    status: "todo",
    priority: "medium",
    assignee: "Clara Hoffmann",
    dueDate: "2025-11-13",
    tags: ["parking", "calculation", "compliance"],
    createdAt: "2025-11-04",
  },
  {
    id: "12",
    title: "Koordiniere Abstimmung mit Umweltamt",
    description:
      'Rücksprache mit Umweltamt bezüglich Bodengutachten und Altlastenverdacht für Projekt „Gewerbegebiet Ost".',
    status: "blocked",
    priority: "high",
    assignee: "Thomas Becker",
    dueDate: "2025-11-07",
    tags: ["environment", "coordination", "soil-analysis"],
    createdAt: "2025-11-01",
  },
  {
    id: "13",
    title: 'Erstelle Baugenehmigung „Mehrfamilienhaus Ost"',
    description: "Alle Prüfungen abgeschlossen, finale Baugenehmigung mit Auflagen erstellen und an Bauherr versenden.",
    status: "in-progress",
    priority: "high",
    assignee: "BauFlowAI",
    dueDate: "2025-11-08",
    tags: ["permit", "approval", "automation"],
    createdAt: "2025-11-02",
  },
  {
    id: "14",
    title: 'Überprüfe Energieausweis „Sanierung Altbau"',
    description:
      "Prüfe eingereichten Energieausweis auf Vollständigkeit und Einhaltung EnEV-Anforderungen für Bestandssanierung.",
    status: "todo",
    priority: "medium",
    assignee: "Clara Hoffmann",
    dueDate: "2025-11-14",
    tags: ["energy", "certificate", "renovation"],
    createdAt: "2025-11-04",
  },
]
